### ISSUE TITLE
Mailer not implementing Illuminate\Contracts\Mail\Factory

### ISSUE THREAD

**Issue by CraftLogan** [beyondcode/helo-laravel#1] opened 2020-04-21 01:29 UTC
message: "Argument 1 passed to Illuminate\Notifications\Channels\MailChannel::__construct() must implement interface Illuminate\Contracts\Mail\Factory, instance of BeyondCode\HeloLaravel\Mailer given"
exception: "TypeError"
file: "/Applications/MAMP/htdocs/dailyeatz/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php"
line: 37

**Comment by CraftLogan** [comment] 2020-04-21 01:30
I am running Laravel Framework 7.1.3

**Comment by mpociot** [comment] 2020-04-21 07:26
Can you tell me how you tested the email notification? Does the test command work for you?

**Comment by zupolgec** [comment] 2020-04-21 09:55
I have a similar issue. When I do a simple `Mail::to('address')->send($mailable)` I get this error:

> Method BeyondCode\HeloLaravel\Mailer::mailer does not exist.

I see that `app('mail.manager')` returns a `Mailer` instead of a `MailManager` that implements `Illuminate\Contracts\Mail\Factory`

**Comment by mpociot** [comment] 2020-04-21 09:56
@zupolgec Which Laravel version are you using?

**Comment by zupolgec** [comment] 2020-04-21 09:59
7.6.2

**Comment by zupolgec** [comment] 2020-04-21 10:14
Maybe it would be better to implement it as a SwiftMailer plugin?

Like it's done here: https://github.com/fedeisas/laravel-mail-css-inliner/blob/master/src/LaravelMailCssInlinerServiceProvider.php

**Comment by mpociot** [comment] 2020-04-21 10:16
Oh cool idea, yeah that's definitely better :)
I didn't know about SwiftMailer plugins!

**Comment by pdewit** [comment] 2020-04-21 10:47
Same issue with Laravel 7.5.2:

`Argument 1 passed to Illuminate\Notifications\Channels\MailChannel::__construct() must implement interface Illuminate\Contracts\Mail\Factory, instance of BeyondCode\HeloLaravel\Mailer given`

**Comment by TiBianMod** [comment] 2020-04-21 11:47
I have the same issue with Laravel 7.6.2

```
TypeError: Argument 1 passed to Illuminate\Mail\SendQueuedMailable::handle() must implement interface Illuminate\Contracts\Mail\Factory, instance of BeyondCode\HeloLaravel\Mailer given...
```

**Comment by beebmx** [comment] 2020-04-21 17:11
I have the same issue with Laravel 7.7.0.
I just use de build-in register from Laravel and implements MustVerifyEmail.

> TypeError: Argument 1 passed to Illuminate\Notifications\Channels\MailChannel::__construct() must implement interface Illuminate\Contracts\Mail\Factory, instance of BeyondCode\HeloLaravel\Mailer given

**Comment by woodymendoza** [comment] 2020-04-21 18:02
Same issue - Laravel 7.6.1

**Comment by TechTailor** [comment] 2020-04-21 19:20
Yup, same issue, 

```
TypeError
Argument 1 passed to Illuminate\Notifications\Channels\MailChannel::__construct() must implement interface Illuminate\Contracts\Mail\Factory, instance of BeyondCode\HeloLaravel\Mailer given
``` 
Using PHP v7.3.16, Laravel v7.7.0

The emails are being sent correctly and displayed in HELO if I am explicitly using something like - 
`Mail::to($user->email)->send(new CustomMail());`
but when using anything build-in like Laravel verification email, getting the above error.

**Comment by patrickbrouwers** [comment] 2020-04-21 19:43
Having the same exception as @TechTailor when sending verification mail. 

Seems due to the mail facade. When I remove the `Mail::swap($instance);` it works again. The Mail facade expects the mail manager and not the mailer instance. I guess this is not an issue in most cases as the manager proxies most calls to the mailer anyway. However in case of the mail channel it seems to need the actual manager instance and it is being resolved via the facade.

Wondering if swapping the actual default mailer in the manager would be the better way to go.

**Comment by stayallive** [comment] 2020-04-21 21:55
The funny thing is also that the [CSS inliner plugin](https://github.com/fedeisas/laravel-mail-css-inliner) mentioned above is broken when this package is active since the mailer is swapped out so all registered plugins are lost.

So +1 on seeing if everything done in this package can be re-implemented as a SwiftMailer plugin.

**Comment by voicecode-bv** [comment] 2020-04-22 06:51
Same issue when sending password reset mails, using 7.6.2.

**Comment by maxacarvalho** [comment] 2020-04-22 15:31
Is there any update about this?  

Basically I cannot use the HELO app since it relies on this package.

**Comment by sschlein** [comment] 2020-04-22 15:33
HELO does not need this package, it is completely optional. You can also use HELO with any other framework or programming language :)

**Comment by maxacarvalho** [comment] 2020-04-22 15:34
@sschlein Well, it's on the HELO documentation when using Laravel, is that unnecessary?

**Comment by sschlein** [comment] 2020-04-22 15:42
@maxacarvalho "You can install the HELO helper package to display additional debug information, like which view file, view content and view data was used when sending the email."

"Can" - but I get your point and will change this asap to make it more clear!

**Comment by crynobone** [comment] 2020-04-23 03:37
https://github.com/beyondcode/helo-laravel/blob/0c17b27772b83bcaf6f66206378c011d21b20db6/src/HeloLaravelServiceProvider.php#L24-L28

The problem occured from `Mail::swap()`, in Laravel 7 it's accessor of `mail.manager` and not `mailer` as in Laravel 6.

**Comment by ulfie22** [comment] 2020-04-23 18:25
HELO works great with all the mail my commands generate; the built-in authentication stuff blows up as above.

**Comment by TechTailor** [comment] 2020-04-23 18:28
> HELO works great with all the mail my commands generate; the built-in authentication stuff blows up as above.

Again i think this needs to be better documented but just remove the helo package from your laravel app and everything will work as intended including the build-in email notifications laravel sends. The issue is with the package and not the HELO App itself.

**Comment by sschlein** [comment] 2020-04-23 19:32
I updated the docs on the site to include the different Laravel 6/7+ configurations and moved the install of the optional package to the bottom of the Laravel configuration so that this is more clear. We'll also change this in the app with the next version!

**Comment by sschlein** [comment] 2020-04-23 19:35
This makes it clearer in the app:

<img width="1150" alt="Bildschirmfoto 2020-04-23 um 21 34 46" src="https://user-images.githubusercontent.com/2911113/80141741-55e18900-85aa-11ea-90d9-b7e1f81a98e6.png">

**Closed** 2020-04-24 07:54 UTC
